import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";


const HostGro = Host_Grotesk({
  subsets: ["latin"],
  variable: "--font-host-grotesk",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${HostGro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
